//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Menees.VsTools.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Menees.VsTools.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; ?&gt;
        ///&lt;ScanInfo&gt;
        ///	&lt;Style Name=&quot;C&quot;&gt;
        ///		&lt;SingleLineDelimiter&gt;//&lt;/SingleLineDelimiter&gt;
        ///		&lt;MultiLineDelimiter Begin=&quot;/*&quot; End=&quot;*/&quot; /&gt;
        ///		&lt;Languages&gt;CPlusPlus, CSharp, IDL, JavaScript, TypeScript&lt;/Languages&gt;
        ///		&lt;Extensions&gt;cs, c, cpp, cxx, cc, java, js, ts, cshtml, h, hpp, inl, idl, tli, tlh, hh, hxx, rc, aspx, ascx, master, asax&lt;/Extensions&gt;
        ///	&lt;/Style&gt;
        ///
        ///	&lt;Style Name=&quot;VB&quot;&gt;
        ///		&lt;SingleLineDelimiter&gt;&apos;&lt;/SingleLineDelimiter&gt;
        ///		&lt;Languages&gt;VB, VBScript&lt;/Languages&gt;
        ///		&lt;Extensions&gt;v [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ScanInfoXml {
            get {
                return ResourceManager.GetString("ScanInfoXml", resourceCulture);
            }
        }
    }
}
